#!/bin/bash
 
###########verifica se o usuario é root##################
#se for root retorna 0
#se for usuario normal retorna 1000
userid=$(id -u)
if [ $userid = 1000 ]; then
	usuario="User"
fi
if [ $userid = 0 ]; then
	usuario="ADM"
fi

appSSH="git@github.com:EdsonOliveira/Ai2LiveMulti-PtBr.git"
appNome="Ai2LiveMulti-PtBr"
DirOrigem="/home/gerente/Desktop/AiHou2/Ai2LiveMulti-PtBr/"
 

################################### Edição de arquivo
function  git_EscolheArquivoAEditar () {
ArqFonte=`zenity --filename="$DirOrigem/" --file-selection --title="Selecione o Arquivo a Editar"`
	case $? in
		1)
			zenity --info --text "Nenhum arquivo selecionado." --title "GIT-APP";;
		-1)
			zenity --info --text "Nenhum arquivo selecionado." --title "GIT-APP";;
		0)
			ArqEditar=(${ArqFonte##*/})
			cd $DirOrigem
			mcedit $ArqFonte
			git status | grep modified >/tmp/210766.txt
			mensagem=$(cat /tmp/210766.txt)
			cat /tmp/210766.txt
			zenity --info --text "$mensagem" --title "GIT-APP"
			rm /tmp/210766.txt
			cd -;;
	esac
}
 
##################################### Adicionar ao projeto
function  git_IncluiAlteracoes () {
 cd $DirOrigem
 dir
 git add .
 zenity --info --text "Arquivos alterados incluídos ao projeto" --title "GIT-APP"
 cd -
}

##################################### Confirma ao projeto
function  git_ConfirmaAlteracoes () {
 cd $DirOrigem
 Descreve=$(zenity --entry --text="Digite a Descrição da Alteração" --title="..::GIT-APP::.." --width=300)
 git commit -a -m "$Descreve" 
 zenity --info --text "Arquivos alterados incluídos ao projeto" --title "GIT-APP"
 cd -
}

##################################### Envia o projeto
function  git_EnviaAlteracoes () {
 cd $DirOrigem
 zenity --info --text "Autenticando e Enviando" --title "GIT-APP" 
 git remote set-url origin $appSSH
 git push origin master
 zenity --info --text "Arquivos enviados ao projeto" --title "GIT-APP"
 cd -
}

##################################### Confirma ao projeto
function  VaiAoDiretorio () {
 cd $DirOrigem
}

##################################### Busca o projeto
function  git_BuscaBase () {
git clone $appSSH 
}

################## MENU DE ESCOLHA #######################
while true; do
  acao="$(zenity --width=550 --height=400 --list --column "   " --title="GIT-APP - $appNome - $usuario" \
   " 1) Buscar Base completa" \
   " 2) Editar um arquivo" \
   " 3) Adicionar ao projeto as alterações" \
   " 4) Confirmar atualizações" \
   " 5) Enviar atualizações" \
   "=> Clique na Escolha e em OK! Ou Cancela e Sai::")"
 
case $acao in
 
" 1) Buscar Base completa")
git_BuscaBase ;;
 
" 2) Editar um arquivo")
git_EscolheArquivoAEditar ;;
 
" 3) Adicionar ao projeto as alterações" )
git_IncluiAlteracoes ;;
 
" 4) Confirmar atualizações" )
git_ConfirmaAlteracoes ;;
 
" 5) Enviar atualizações" )
git_EnviaAlteracoes ;;
 
*) exit ;;
 
esac
 
done

